<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2021 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use T4\Helper\J3J4;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
JHtml::_('bootstrap.tooltip');
if(version_compare(JVERSION, '4','lt')){
JHtml::_('behavior.framework');
}

require_once(__DIR__.'/../../../helper.php');

// Create a shortcut for params.
$params = $this->item->params;
$images  = json_decode($this->item->images);
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

$aInfo1 = ($params->get('show_publish_date') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author'));
$aInfo2 = ($params->get('show_create_date') || $params->get('show_modify_date') || $params->get('show_hits'));
$topInfo = ($aInfo1 && $info != 1) || ($aInfo2 && $info == 0);
$botInfo = ($aInfo1 && $info == 1) || ($aInfo2 && $info != 0);
$icons = $params->get('access-edit') || $params->get('show_print_icon') || $params->get('show_email_icon');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

if(version_compare(JVERSION, '4', 'ge')){
  $currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
  $isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
  $isNotPublishedYet = $this->item->publish_up > $currentDate;
  $isUnpublished     = $this->item->state == ContentComponent::CONDITION_UNPUBLISHED || $isNotPublishedYet || $isExpired;
}else{
  $isExpired         = (strtotime($this->item->publish_down) < strtotime(Factory::getDate())) && $this->item->publish_down != Factory::getDbo()->getNullDate();
  $isNotPublishedYet = strtotime($this->item->publish_up) > strtotime(Factory::getDate());
  $isUnpublished     = J3J4::checkUnpublishedContent($this->item);
}

// update catslug if not exists - compatible with 2.5
if (empty ($this->item->catslug)) {
  $this->item->catslug = $this->item->category_alias ? ($this->item->catid.':'.$this->item->category_alias) : $this->item->catid;
}

// Get Extrafields
$extrafields = new JRegistry($this->item->attribs);
$teamNumber = $extrafields->get('number');
$teamPosition = $extrafields->get('team_position');

?>

<!-- Article -->
<article class="view-player">
 <?php if ($isUnpublished) : ?>
    <div class="system-unpublished">
  <?php endif; ?>

    <div class="image-wrap">
      <?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
    </div>

    <div class="intro-wrap">
      <div class="top-info">
        <div class="short-info-player">
          <?php if($teamNumber) :?>
          <div class="t-number">
            <?php echo $teamNumber ;?>
          </div>
          <?php endif; ?>

          <div class="t-name">
            <?php echo LayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item); ?>

            <?php if($teamPosition) :?>
            <div class="t-position">
              <?php echo $teamPosition ;?>
            </div>
            <?php endif; ?>
          </div>
        </div>

        <?php if (!$params->get('show_intro')) : ?>
          <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
          <?php echo $this->item->event->afterDisplayTitle; ?>
        <?php endif; ?>

        <!-- Aside -->
        <?php if ($topInfo || $icons) : ?>
        <aside class="article-aside clearfix">
          <?php if ($topInfo): ?>
          <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
          <?php endif; ?>
          
          <?php if ($icons): ?>
          <?php echo JLayoutHelper::render('joomla.content.icons', array('item' => $this->item, 'params' => $params)); ?>
          <?php endif; ?>
        </aside>  
        <?php endif; ?>
        <!-- //Aside -->

        <?php if ($params->get('show_intro')) : ?>
        <div class="item-intro">
          <?php echo $this->item->introtext; ?>
        </div>
        <?php endif; ?>
        <!-- footer -->
        <?php if ($botInfo) : ?>
        <footer class="article-footer clearfix">
          <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
          <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
        </footer>
        <?php endif; ?>
        <!-- //footer -->
      </div>
    </div>
  <?php if ($isUnpublished) : ?>
    </div>
  <?php endif; ?>

</article>
<!-- //Article -->


